swagger: '2.0'
info:
  description: ''
  version: 1.0.0
  title: D4D Project API Server Swagger
  termsOfService: ''
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: '13.125.196.191:4400'
basePath: /api/v1
tags:
  - name: User
    description: 사용자
  - name: Project
    description: 프로젝트
  - name: Skill-Code
    description: 기술코드
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User
      summary : 로그인
      description : 로그인
      parameters :
        - in : body
          name : body
          description : 사용자 정보
          required : true    
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 사용자 고유 id
              email:
                type: string
                description: 이메일
              snsType:
                type: string
                description: 소셜로그인 종류
              nickName:
                type: string
                description: 닉네임
      responses:
        '200':
          description : 회원 정보
          schema:
            type : object
            properties :
              userId:
                type: string
                description: 사용자 고유 id
              email:
                type: string
                description: 이메일
              nickName:
                type: string
                description: 닉네임
              realName:
                type: string
                description: 실명
              snsType:
                type: string
                description: 소셜로그인 종류
        '500':
          description: 로그인 실패
  /skill-code/list:
    get:
      tags:
        - Skill-Code
      summary : 기술코드 목록 조회
      description : 기술코드 목록 조회
      parameters :
        - in : query
          name : type
          description : 기술코드 종류 ("designer" or "developer")
          required : true
      responses:
        '200':
          description : 기술코드 목록
          schema:
            type : object
            properties :
              codeType:
                type: string
                description: 기술코드 목록 구분 ("designer" or "developer")
              items:
                type: array
                items:
                  type: object
                  description: 코드 목록
                  properties:
                    code: 
                      type: string
                      description: 기술코드
                    codeName:
                      type: string
                      description: 기술코드명
        '500':
          description: 기술코드 목록 조회 실패
  /project:
    post:
      tags:
        - Project
      summary : 프로젝트 생성
      description : 프로젝트 생성
      consumes:
        - multipart/form-data
      parameters :
        - name: attachments
          in: formData
          description: 첨부파일
          required: false
          type: file
        - name: userId
          in: formData
          description: 사용자 고유 id (=작성자)
          required: true
          type: string
        - name: title
          in: formData
          description: 제목
          required: true
          type: string
        - name: text
          in: formData
          description: 내용
          required: true
          type: string
        - name: text
          in: formData
          description: 내용
          required: true
          type: string
        - name: startDate
          in: formData
          description: 프로젝트 시작일시
          required: true
          type: string
        - name: endDate
          in: formData
          description: 프로젝트 종료일시
          required: true
          type: string
        - name: skillCodeDesigner
          in: formData
          description: 기술코드목록 (디자이너) (Ex. "['DESIGNER_SKILL_CODE_1','DESIGNER_SKILL_CODE_3']")
          required: true
          type: string
        - name: skillCodeDeveloper
          in: formData
          description: 기술코드목록 (개발자) (Ex. "['DEVELOPER_SKILL_CODE_1','DEVELOPER_SKILL_CODE_2']")
          required: true
          type: string
      responses:
        '200':
          description : 프로젝트 상세 정보
          schema:
            type : object
            properties :
        '500':
          description: 프로젝트 생성 실패