swagger: '2.0'
info:
  description: ''
  version: 1.0.0
  title: D4D Project API Server Swagger
  termsOfService: ''
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: '13.125.196.191:4400'
basePath: /api/v1
tags:
  - name: User
    description: 사용자
  - name: Project
    description: 프로젝트
  - name: Skill-Code
    description: 기술코드
  - name: Message
    description: 쪽지
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User
      summary : 로그인
      description : 로그인
      parameters :
        - in : body
          name : body
          description : 사용자 정보
          required : true    
          schema:
            type: object
            properties:
              userId:
                type: string
                description: 사용자 고유 id
              email:
                type: string
                description: 이메일
              snsType:
                type: string
                description: 소셜로그인 종류
              nickName:
                type: string
                description: 닉네임
      responses:
        '200':
          description : 회원 정보
          schema:
            type : object
            properties :
              userId:
                type: string
                description: 사용자 고유 id
              email:
                type: string
                description: 이메일
              nickName:
                type: string
                description: 닉네임
              realName:
                type: string
                description: 실명
              snsType:
                type: string
                description: 소셜로그인 종류
              profileImage:
                type: string
                description: 프로필 이미지 URL
        '500':
          description: 로그인 실패
  /skill-code/list:
    get:
      tags:
        - Skill-Code
      summary : 기술코드 목록 조회
      description : 기술코드 목록 조회
      parameters :
        - in : query
          name : type
          description : 기술코드 종류 ("designer" or "developer")
          required : true
      responses:
        '200':
          description : 기술코드 목록
          schema:
            type : object
            properties :
              codeType:
                type: string
                description: 기술코드 목록 구분 ("designer" or "developer")
              items:
                type: array
                items:
                  type: object
                  description: 코드 목록
                  properties:
                    code: 
                      type: string
                      description: 기술코드
                    codeName:
                      type: string
                      description: 기술코드명
        '500':
          description: 기술코드 목록 조회 실패
  /project:
    post:
      tags:
        - Project
      summary : 프로젝트 생성
      description : 프로젝트 생성
      consumes:
        - multipart/form-data
      parameters :
        - name: attachments
          in: formData
          description: 첨부파일
          required: false
          type: file
        - name: userId
          in: formData
          description: 사용자 고유 id (=작성자)
          required: true
          type: string
        - name: title
          in: formData
          description: 제목
          required: true
          type: string
        - name: text
          in: formData
          description: 내용
          required: true
          type: string
        - name: text
          in: formData
          description: 내용
          required: true
          type: string
        - name: startDate
          in: formData
          description: 프로젝트 시작일시 (YYYY-MM-DD)
          required: true
          type: string
        - name: endDate
          in: formData
          description: 프로젝트 종료일시 (YYYY-MM-DD)
          required: true
          type: string
        - name: skillCodeDesigner
          in: formData
          description: 기술코드목록 (디자이너) (Ex. "['DESIGNER_SKILL_CODE_1','DESIGNER_SKILL_CODE_3']")
          required: true
          type: string
        - name: skillCodeDeveloper
          in: formData
          description: 기술코드목록 (개발자) (Ex. "['DEVELOPER_SKILL_CODE_1','DEVELOPER_SKILL_CODE_2']")
          required: true
          type: string
      responses:
        '200':
          description: 프로젝트 상세 정보
          schema:
            type: object
            properties:
              projectInfo:
                type: object
                description: 프로젝트 상세정보
                properties:
                  projectId:
                    type: string
                    description: 프로젝트 고유 id
                  skill:
                    type: object
                    properties:
                      designer:
                        type: array
                        description: 디자이너 기술 목록
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                              description: 기술코드
                            codeName:
                              type: string
                              description: 기술코드명
                      developer:
                        type: array
                        description: 개발자 기술 목록
                        items:
                          type: object
                          properties:
                            code:
                              type: string
                              description: 기술코드
                            codeName:
                              type: string
                              description: 기술코드명
                  hits:
                    type: number
                    description: 조회수
                  title:
                    type: string
                    description: 제목
                  text:
                    type: string
                    description: 내용
                  startDate:
                    type: string
                    description: 프로젝트 시작날짜 (YYYY-MM-DD)
                  endDate:
                    type: string
                    description: 프로젝트 끝날짜 (YYYY-MM-DD)
                  attachments:
                    type: array
                    description: 첨부파일 목록
                    items:
                      type: object
                      properties:
                        fileName:
                          type: string
                          description: 파일명
                        downloadUrl:
                          type: string
                          description: 다운로드 URL
              writerInfo:
                type: object
                description: 작성자(PM) 정보
                properties:
                  writerId:
                    type: string
                    description: 사용자 고유 id
                  nickName:
                    type: string
                    description: 닉네임
              isWriter:
                type: boolean
                description: 작성자 여부
        '500':
          description: 프로젝트 생성 실패
  /project/list/main:
    get:
      tags:
        - Project
      summary : 메인 프로젝트 목록 조회
      description : 메인 프로젝트 목록 조회
      parameters :
        - in : query
          name : page
          description : 페이지 번호 (default:1)
          required : false
        - in : query
          name : perPage
          description : 페이지당 아이템 개수 (default:3)
          required : false
      responses:
        '200':
          description : 프로젝트 목록 및 페이지 정보
          schema:
            type : object
            properties:
              projectList:
                type: array
                description: 프로젝트 목록
                items:
                  type: object
                  description: 프로젝트 정보
                  properties:
                    title:
                      type: string
                      description: 제목
                    text:
                      type: string
                      description: 내용
                    startDate:
                      type: string
                      description: 프로젝트 시작날짜 (YYYY-MM-DD)
                    endDate:
                      type: string
                      description: 프로젝트 끝날짜 (YYYY-MM-DD)
                    hits:
                      type: number
                      description: 조회수
                    applicantCount:
                      type: number
                      description: 지원자수
                    writerId:
                      type: string
                      description: 작성자 고유 id
                    writerInfo:
                      type: object
                      description: 작성자 정보
                      properties:
                        profileImage:
                          type: string
                          description: 프로필 이미지 URL
                        nickName:
                          type: string
                          description: 닉네임
              currentPage:
                type: number
                description: 현재 페이지 번호 (1~)
              lastPage:
                type: number
                description: 마지막 페이지 번호
              totalCount:
                type: number
                description: 전체 프로젝트 개수 
        '500':
          description: 메인 프로젝트 목록 조회 실패
  /user/profile:
    get:
      tags:
        - User
      summary : 프로필 정보 조회
      description : 프로필 정보 조회
      parameters :
        - in : query
          name : userId
          description : 사용자 고유 id
          required : true
      responses:
        '200':
          description : 프로필 정보
          schema:
            type : object
            properties :
              userId:
                type: string
                description: 사용자 고유 id
              email:
                type: string
                description: 이메일
              nickName:
                type: string
                description: 닉네임
              realName:
                type: string
                description: 실명
              snsType:
                type: string
                description: 소셜로그인 구분
              profileImage:
                type: string
                description: 프로필 이미지 URL
              introduction:
                type: string
                description: 자기소개
              skill:
                type: object
                properties:
                  designer:
                    type: array
                    description: 디자이너 기술 목록
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          description: 기술코드
                        codeName:
                          type: string
                          description: 기술코드명
                  developer:
                    type: array
                    description: 개발자 기술 목록
                    items:
                      type: object
                      properties:
                        code:
                          type: string
                          description: 기술코드
                        codeName:
                          type: string
                          description: 기술코드명
        '500':
          description: 프로필 정보 조회 실패
  /message/send:
    post:
      tags:
        - Message
      summary : 쪽지 보내기
      description : 쪽지 보내기
      parameters :
        - in : body
          name : body
          description : 쪽지 정보
          required : true    
          schema:
            type: object
            properties:
              senderId:
                type: string
                description: 보낸이 고유 id
              receiverId:
                type: string
                description: 받는이 고유 id
              title:
                type: string
                description: 쪽지 제목
              content:
                type: string
                description: 쪽지 내용
      responses:
        '200':
          description : 쪽지 전송 성공
          schema:
            type : object
            properties :
              code:
                type: string
                description: "suc_send_message"
              message:
                type: string
                description: "쪽지 전송 성공"
        '500':
          description: 쪽지 전송 실패
  /message/list/received:
    get:
      tags:
        - Message
      summary : 나의 받은쪽지함 목록 조회
      description : 나의 받은쪽지함 목록 조회
      parameters :
        - in : query
          name : userId
          description : 사용자 고유 id
          required : true
        - in : query
          name : page
          description : 페이지 번호 (default:1)
          required : false
        - in : query
          name : perPage
          description : 페이지당 아이템 개수 (default:10)
          required : false
      responses:
        '200':
          description : 쪽지 목록
          schema:
            type : object
            properties :
              currentPage:
                type: number
                description: 현재 페이지 번호
              lastPage:
                type: number
                description: 마지막 페이지 번호
              totalCount:
                type: number
                description: 총 아이템 개수
              messageList:
                type: array
                description: 쪽지 목록
                items:
                  type: object
                  properties:
                    messageId:
                      type: string
                      description: 쪽지 고유 id
                    title:
                      type: string
                      description: 쪽지 제목
                    content:
                      type: string
                      description: 쪽지 내용 (10글자)
                    receiveDate:
                      type: string
                      description: 쪽지 받은 날짜
                    senderNickName:
                      type: string
                      description: 보낸이 닉네임
                    senderId:
                      type: string
                      description: 보낸이 고유 id
                    isRead:
                      type: boolean
                      description: 읽음 여부
        '500':
          description: 나의 받은쪽지함 목록 조회
  /message/list/sent:
    get:
      tags:
        - Message
      summary : 나의 보낸쪽지함 목록 조회
      description : 나의 보낸쪽지함 목록 조회
      parameters :
        - in : query
          name : userId
          description : 사용자 고유 id
          required : true
        - in : query
          name : page
          description : 페이지 번호 (default:1)
          required : false
        - in : query
          name : perPage
          description : 페이지당 아이템 개수 (default:10)
          required : false
      responses:
        '200':
          description : 쪽지 목록
          schema:
            type : object
            properties :
              currentPage:
                type: number
                description: 현재 페이지 번호
              lastPage:
                type: number
                description: 마지막 페이지 번호
              totalCount:
                type: number
                description: 총 아이템 개수
              messageList:
                type: array
                description: 쪽지 목록
                items:
                  type: object
                  properties:
                    messageId:
                      type: string
                      description: 쪽지 고유 id
                    title:
                      type: string
                      description: 쪽지 제목
                    content:
                      type: string
                      description: 쪽지 내용 (10글자)
                    sendDate:
                      type: string
                      description: 쪽지 받은 날짜
                    receiverNickName:
                      type: string
                      description: 받는이 닉네임
                    receiverId:
                      type: string
                      description: 받는이 고유 id
                    receiverIsRead:
                      type: boolean
                      description: 받는이 여부 여부
        '500':
          description: 나의 보낸쪽지함 목록 조회